Repository xlab-si/xopera-opera, pull requests merged in 2020-08, with the labels that each got.

#87 Leftover library extraction: state handling
  src/opera/commands/deploy.py
  src/opera/commands/init.py
Labels: bug

#70 Include verbose mode for opera CLI commands
  src/opera/commands/deploy.py
  src/opera/commands/init.py
  src/opera/commands/outputs.py
  src/opera/commands/undeploy.py
  src/opera/commands/validate.py
  src/opera/executor/ansible.py
  src/opera/instance/base.py
  src/opera/instance/node.py
  src/opera/instance/topology.py
  src/opera/template/node.py
  src/opera/template/operation.py
  src/opera/template/relationship.py
  src/opera/threading/node_executor.py
Labels: enhancement

#60 Introduce the very first opera documentation
  .circleci/config.yml
  Makefile
  Pipfile
  docs/business-value.rst
  docs/conf.py
  docs/documentation.rst
  docs/examples.rst
  docs/images/opera_deploy_cli.png
  docs/images/opera_parser_structure.png
  docs/index.rst
  docs/installation.rst
  docs/introduction.rst
Labels: enhancement

#67 Supplement get_artifact TOSCA function
  examples/artifacts/files/file.txt
  examples/artifacts/playbooks/create.yaml
  examples/artifacts/service.yaml
  src/opera/executor/ansible.py
  src/opera/instance/node.py
  src/opera/instance/relationship.py
  src/opera/parser/tosca/v_1_3/artifact_definition.py
  src/opera/parser/tosca/v_1_3/collector_mixin.py
  src/opera/parser/tosca/v_1_3/definition_collector_mixin.py
  src/opera/parser/tosca/v_1_3/node_template.py
  src/opera/template/node.py
  src/opera/template/operation.py
  src/opera/template/topology.py
  src/opera/value.py
Labels: enhancement, help wanted

#95 Fix documentation deployment errors when having no changes in docs
  .circleci/config.yml
Labels: bug, help wanted
