Repository xlab-si/xopera-opera, pull requests merged in 2021-01, with the labels that each got.

#159 Specify README format in setup.cfg
  setup.cfg
  setup.py
Labels: bug

#156 Add update command
  src/opera/commands/__init__.py
  src/opera/commands/diff.py
  src/opera/commands/update.py
  src/opera/compare/diff.py
  src/opera/compare/instance_comparer.py
  src/opera/instance/base.py
  src/opera/instance/topology.py
  src/opera/utils.py
  tests/integration/compare/runme.sh
  tests/unit/opera/compare/test_instance_compare.py
Labels: enhancement

#90 Use occurrences keyname to control usage of requirements
  examples/attribute_mapping/service.yaml
  src/opera/parser/tosca/v_1_3/node_template.py
  src/opera/parser/tosca/v_1_3/range.py
  src/opera/template/node.py
  src/opera/template/requirement.py
  tests/integration/concurrency/service.yaml
Labels: enhancement

#162 Fix xOpera documentation project name
  docs/conf.py
Labels: enhancement

#142 Introduce opera tab completion
  requirements.txt
  setup.cfg
  src/opera/cli.py
  src/opera/commands/deploy.py
  src/opera/commands/info.py
  src/opera/commands/init.py
  src/opera/commands/outputs.py
  src/opera/commands/package.py
  src/opera/commands/undeploy.py
  src/opera/commands/unpackage.py
  src/opera/commands/validate.py
Labels: enhancement

#153 Specialise directory and file based csars in classes
  src/opera/commands/deploy.py
  src/opera/commands/init.py
  src/opera/commands/package.py
  src/opera/commands/unpackage.py
  src/opera/commands/validate.py
  src/opera/parser/tosca/csar.py
  src/opera/utils.py
Labels: enhancement

#154 Stateless info
  src/opera/commands/deploy.py
  src/opera/commands/info.py
  src/opera/commands/undeploy.py
Labels: enhancement

#167 Make maxsize property optional for TOSCA ObjectStorage normative type
  src/opera/stdlib/v_1_3.yaml
Labels: TOSCA issue, invalid
